general:
    progress: logged

# CHANGE THIS (MANDATORY)
model:
    offset: +LearnableOffset()
    many-body:
        # SPECIFY ARCHITECTURE e.g. "+NequIP:"
            elements: [C]
            cutoff: 3.7 # YOU CAN CHANGE THIS (OPTIONAL)
            # SPECIFY HYPERPARAMETERS (MANDATORY- please read documentation!)

# direct model towards the datafiles we've just made ...
data:
    train:
            path: train.xyz
            n: 1200 # we don't use the full training set here to minimise training time
            shuffle: true
            cutoff: =/CUTOFF
    valid: 
            path: valid.xyz
            cutoff: =/CUTOFF
    test: 
            path: test.xyz
            cutoff: =/CUTOFF

# specify loss function
# here we weight energy and forces 1:1 - you can change this!
loss:
    - +PerAtomEnergyLoss()
    - +ForceRMSE()

# specify training protocol
# key parameters here are the learning rate, batch size, and max_epochs- you can experiment with different values!
fitting:
    trainer_kwargs:
        max_epochs: 100 # we keep this small for the purposes of this class, in practice you should let your models train to completion
        accelerator: auto 
        check_val_every_n_epoch: 1

    optimizer:
            name: AdamW
            lr: 0.01 # YOU CAN CHANGE THIS (OPTIONAL)

    scheduler:
            name: ReduceLROnPlateau
            factor: 0.5
            patience: 10

    loader_kwargs:
        batch_size: 16 # YOU CAN CHANGE THIS (OPTIONAL)

wandb: null
